item {
  id: 1
  name: 'Circle'
}

item {
  id: 2
  name: 'Straight'
}

item {
  id: 3
  name: 'Left'
}

item {
  id: 4
  name: 'Right'
}

item {
  id: 5
  name: 'Pedestrian'
}

item {
  id: 6
  name: 'Bike'
}
item {
  id: 7
  name: 'Bus'
}
